alumet-dev/alumet

- plugin-influxdb/src/lib.rs
> fix(plugin-influxdb): Skip empty MeasurementBuffers in `write`

- alumet/Cargo.toml
- alumet/src/agent.rs
It is now possible to any linux environment variable in the config files if the variable does exist and isn't empty. You can obviously escape the `$` symbol with a backslash to use it.
Some tests has been added to ensure that the regex is working correctly and that a breaking change will never be able to happen.
> feat(alumet): Add environment variable interpolation for config files

- plugin-energy-attribution/src/lib.rs
The name of the cgroup's metrics have been changed, so we need to change it too in the plugin-energy-atribution to make it works again...
`total_usage_usec` => `cgroup_cpu_usage_user`
> fix(plugin-energy-attribution): Change the cgroup metric name in the pre_pipeline_start

- plugin-cgroupv2/src/k8s/utils.rs
In the code, when cgroupv2 files are detected, check if it's don't end with ".slice". If not, just look at the next file. 
Fix #50
> fix(plugin_k8s): don't explore folder which don't end with .slice

- app-agent/Cargo.toml
- app-agent/src/options.rs
Fix #59
You can now use both:
- *--config path/to/config/file*
- *export CONFIG=path/to/config/file*
To use alumet
> feat(options): config can be passed as environment variable now

- Cargo.lock
- plugin-procfs/Cargo.toml
- plugin-procfs/src/lib.rs
Automatically increase alumet process's file descriptors soft limit when plugin-procfs starts in order to prevent 'Too many open files' error that happened because procfs plugin opens lot of files.
It starts without condition (we could, later, add a configuration option - plugin side - to disable this behavior in some scenarios where administrator would like to manage this limit precisely).
The current implementation will check for the process hard limit and will update soft limit to reach the hard limit. This way the user has still control on the overall process limit - by defining the hard limit.
A future implementation could also be located in Alumet's core to perform the same operation for all the plugins.
> plugin-procfs automatically increases file descriptors soft limit

- Cargo.lock
- alumet/Cargo.toml
- alumet/src/metrics/duplicate.rs
- alumet/src/metrics/error.rs
- alumet/src/metrics/mod.rs
- alumet/src/metrics/online.rs
- alumet/src/metrics/registry.rs
- alumet/src/pipeline/builder.rs
- alumet/src/pipeline/control/main_loop.rs
- alumet/src/pipeline/control/messages.rs
- alumet/src/pipeline/control/request/create.rs
- alumet/src/pipeline/control/request/output.rs
- alumet/src/pipeline/control/request/source.rs
- alumet/src/pipeline/control/request/transform.rs
- alumet/src/pipeline/elements/output/builder.rs
- alumet/src/pipeline/elements/output/control.rs
- alumet/src/pipeline/elements/output/run.rs
- alumet/src/pipeline/elements/source/control.rs
- alumet/src/pipeline/elements/source/task_controller.rs
- alumet/src/pipeline/util/channel.rs
- alumet/src/pipeline/util/stream.rs
- alumet/src/plugin/phases.rs
- alumet/src/test/runtime.rs
- alumet/tests/metric_duplicates.rs
- plugin-aggregation/src/lib.rs
- plugin-relay/src/server/metrics.rs
New options to choose (not always available in public plugin API, on purpose):
- `DuplicateCriteria`: defines the rules that make a new metric a duplicate.
- `DuplicateReaction`: what to do when there is a duplicate
Resolves #137.
> Make metric registration more configurable

- .github/workflows/release.yaml
This will add the necessary steps to build and push docker images to GHCR.
Note that for now pushing to ghcr is in hard and we could iterate later to push to other repositories (tag part is in alumet-dev/packaging and login part in alumet-dev/alumet .
> add docker images build/push to release action

- plugin-opentelemetry/src/lib.rs
- plugin-opentelemetry/src/output.rs
This way the user can configure how often (in secs) the metrics are pushed to the OTEL collector.
> Push interval in opentelemetry plugin

- .github/workflows/release.yaml
Add concurrency for only one run of workflow.
> ci(release): add concurrency for only one run of workflow

- .github/workflows/release.yaml
Only trigger on publish event.
See more [here ](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release)
> ci(release): change trigger for CI workflow

- Cargo.lock
- agent/Cargo.toml
- agent/src/bin/main.rs
- plugin-energy-estimation-tdp/src/lib.rs
The difference with v0.8.0 is that I've enabled aggregation, energy-attribution and energy-estimation-tdp in alumet-agent.
> Quick 0.8.1 release

- plugin-procfs/src/lib.rs
- plugin-procfs/src/process.rs
Modifies plugin-procfs in order to standardize naming / units and attributes of different plugins producing the same metrics.
> refactor(plugin-procfs): standardize plugin-procfs metrics - cpu and memory metrics

- .circleci/config.yml
- Cargo.lock
- plugin-cgroupv2/Cargo.toml
- plugin-cgroupv2/src/cgroupv2.rs
- plugin-cgroupv2/src/k8s/plugin.rs
- plugin-cgroupv2/src/k8s/probe.rs
- plugin-cgroupv2/src/k8s/utils.rs
- plugin-cgroupv2/src/oar3/plugin.rs
- plugin-cgroupv2/src/oar3/probe.rs
- plugin-cgroupv2/src/oar3/utils.rs
This PR aims to harmonize collected metrics with plugins cgroupv1 and procfs.
In that direction we kept only one cpu related metric called `cpu_time_delta` and gather old cgroup_cpu_usage_total, cgroup_cpu_usage_user and cgroup_cpu_usage_system that are still collected but as a single metric with different `kind` attributes (total, usage and system).
Also added a new metric `memory_usage`.
This metric is sourced from memory.current file from cgroupv2.
It represents the resident (RSS) memory (kind attribute), that makes it consistend with metrics collected in cgroupv1 and procfs.
Removed the metric cgroup_memory_total that was calculated based on other cgroup_memory measurements, since it's recommended to collect memory.current to have the total memory currently used by a process (a bit …
> Refactor cgroupv2 plugin - metrics harmonization

- .github/workflows/check_doc.yaml
- .github/workflows/check_git.yaml
A new action enforces the model "rebase, then merge" where each feature branch has a linear history, but can be merged into master with a merge commit. If the PR branch contains a merge commit, the check will fail.
> ci: Ensure that the git history of each PR branch is linear

- .circleci/config.yml
It takes too much time for not much gain, at least at the moment. We could put it back later if we see some spam.
> feat(ci): Stop requiring a manual validation

- plugin-cgroupv1/src/cgroupv1.rs
Resolve issue while oar2 is  not harmonized with other plugins for **memory_usage** and **cpu_time_delta** metrics which have missing attributes.
> feat(plugin-oar2): add attributes to harmonize with other plugins

- alumet/src/units.rs
- plugin-nvidia-nvml/src/nvml/features.rs
- plugin-nvidia-nvml/src/nvml/metrics.rs
- plugin-nvidia-nvml/src/nvml/probe.rs
Old way to collect process related measurements was buggy, cause it was using pid instead of a unix timestamp in `process_utilization_stats` method. This lead to unexpected values.
Now the source/probe will keep an Option<Timestamp> in memory that contains the timestamp of the last poll. This is helpful to ask `process_utilization_stats` the values since this timestamp.
Also added a new Unit called `Percent`.
> fix(plugin-nvidia-nvml): change the way to collect process related measurements

- .github/workflows/check_git.yaml
- Cargo.lock
- plugin-rapl/Cargo.toml
- plugin-rapl/src/consistency.rs
- plugin-rapl/src/cpus.rs
- plugin-rapl/src/domains.rs
- plugin-rapl/src/lib.rs
- plugin-rapl/src/perf_event.rs
- plugin-rapl/src/powercap.rs
- plugin-rapl/src/tests_mock.rs
Added new unit tests to increase the tested code coverage (up to 70% now).
In order to do so I've done some refactoring, in particular:
- get a global consistency on how powercap and perf_event are initialized and the kind of objects they return
- removed old `PowerZoneHierarchy` that was actually not used in the plugin: now we just use the "flat" version, "top" was removed. This makes it consistent with powercap objects.
- simulate perf_event_open syscall using `nix` library in order to make unit testing of perf_event
- added new configs only available in tests to be able to pass path containing mocked data
- rewrite some functions that was not test-ready because of hardcoded constant paths.
Note that `perf_events` is only partially tested yet, we still miss integration tests for it. …
> tests(plugin-rapl): refactored and added unit + integration tests

- Cargo.lock
- plugin-nvidia-jetson/Cargo.toml
- plugin-nvidia-jetson/README.md
- plugin-nvidia-jetson/src/ina.rs
- plugin-nvidia-jetson/src/ina/common.rs
- plugin-nvidia-jetson/src/ina/modern.rs
- plugin-nvidia-jetson/src/ina/old.rs
- plugin-nvidia-jetson/src/lib.rs
- plugin-nvidia-jetson/src/source.rs
Resolves #212 
Summary:
- cleaner code with new modules: common, modern, old
- unification of the metrics across system versions
- more robust sensor exploration: don't stop at the first error
- detection of invalid entries (on startup): if a sysfs file that should provide measurement doesn't work, skip it (in the previous versions, the entries were not tested and crashed the Alumet source)
> fix(plugin-jetson): refactor the Jetson plugin and make it more robust to errors

- Cargo.lock
- Cargo.toml
- agent/Cargo.toml
- agent/src/bin/main.rs
- plugin-process-to-cgroup-bridge/Cargo.toml
- plugin-process-to-cgroup-bridge/README.md
- plugin-process-to-cgroup-bridge/src/lib.rs
- plugin-process-to-cgroup-bridge/src/tests.rs
- plugin-process-to-cgroup-bridge/src/transform.rs
Add a new **Transform** plugin called `process-to-cgroup-bridge`.
This plugin aims to be enabled when `plugin-nvidia-nvml` (input) is enable.
It will find the cgroup related to the process measurement and will set it as the measurement consumer.
The plugin come with configuration:
- ability to filter the metrics impacted by this plugin
- ability to merge the measurements coming from different processes but with same cgroup at same timestamp
- ability to not keep measurements that have been transformed
The plugin also comes with integration tests that have been placed under `src` because needed some `#[cfg(test)]` tags that are not available in `tests` subdir.
> feat(plugin-process-to-cgroup-bridge): create new plugin

- alumet/src/pipeline/control/request.rs
- alumet/src/pipeline/control/request/create.rs
- alumet/src/pipeline/elements/source.rs
- alumet/src/pipeline/elements/source/builder.rs
- alumet/src/pipeline/elements/source/control.rs
- alumet/src/pipeline/elements/source/run.rs
- alumet/src/pipeline/elements/source/task_controller.rs
- alumet/src/plugin/phases.rs
- alumet/tests/errors/plugin.rs
This PR make possible to add a new source in pause mode.
A plugin can use new method `add_source_with_state` and set the initial_state parameter to pause.
This is useful to ask Alumet monitor sources only if you explicitely ask it (by resuming paused source afterwards).
Note: 
- In current implementation, sources started in pause mode can be resumed for 1 minute
- Tests for this behavior are missing. RuntimeExpectations don't allow to test such behavior cause it automatically resume the sources.
> feat(core): start a source in pause mode

- .github/workflows/release.yaml
Depends on https://github.com/alumet-dev/packaging/pull/19 to enable automatic multi-arch docker images. 
Working with RPM-based images, pending to implement deb
Example in my fork using the artifacts from https://github.com/guigomcha/alumet-packaging/actions/runs/16568037066/job/46853651107:
```bash
docker manifest inspect ghcr.io/guigomcha/alumet-agent:0.0.0-1_ubi9.5
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1993,
"digest": "sha256:9e1574c655cb1f2bf8c9bb83e65d6fbfdb5bc2eb35dc8687d163eca484b6ae18",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1993, …
```
> ci: multi-arch docker images

- core/alumet/src/pipeline/elements/output/control.rs
- core/alumet/tests/build_output.rs
> fix(core): Build outputs in the context of their tokio runtime

- Cargo.toml
- plugins/cgroups/slurm/src/attr.rs
- plugins/cgroups/slurm/src/source.rs
add the specification if it's a job or a step in slurm plugin.
It returns in attribute: 
- `job` if it's the main job
- `step` if it's a step of the job
Fix #266
> feat(slurm): Is it a job or a step

- Cargo.lock
- plugins/kwollect-input/Cargo.toml
- plugins/kwollect-input/README.md
- plugins/kwollect-input/src/lib.rs
- plugins/kwollect-input/src/source.rs
This PR introduces significant improvements to the Kwollect Input Plugin:
- Extended metrics support: Enables the use of nearly all Kwollect metrics (excluding Prometheus exporter metrics, which are already handled by a [dedicated plugin](https://github.com/alumet-dev/alumet/tree/main/plugins/prometheus-exporter)).
- UTC offset configuration: Replaces static system time configuration with a flexible UTC offset setting.
- Robust timestamp parsing: Supports timestamps with varying precision (nanoseconds, microseconds, milliseconds, and no fractions).
**Goal**: Enable the use of nearly all Kwollect metrics, with units normalized to the UCUM standard.
- Added support for standard UCUM units (e.g., `watt` → `W`, `celsius` → `Cel`).
- Added handling for non-UCUM units (e.g., `VA` → `V.A`, `VAr` …
> refactor(plugin-kwollect-input): enhance metrics, timestamp, and timezone configuration

- agent/tests/local.rs
- core/alumet/src/agent/builder.rs
- core/alumet/src/agent/plugin.rs
- core/alumet/src/plugin/mod.rs
> When a plugin is initialized without a config, use its default config
